apiVersion: apps/v1
kind: Deployment
metadata:
  name: skmirza-backend-deploy
  namespace: wanderlust
  labels:
    app: skmirza-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skmirza-backend
  template:
    metadata:
      name: skmirza-backend
      labels:
        app: skmirza-backend
    spec:
      containers:
        - name: skmirza-backend
          image: sameer014/skmirza-wanderlust-backend:1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: skmirza-backend-service
  namespace: wanderlust
spec:
  type: NodePort
  selector:
    app: skmirza-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31100
