apiVersion: apps/v1
kind: Deployment
metadata:
  name: skmirza-frontend-deploy
  namespace: wanderlust
  labels:
    app: skmirza-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skmirza-frontend
  template:
    metadata:
      name: skmirza-frontend
      labels:
        app: skmirza-frontend
    spec:
      containers:
        - name: skmirza-frontend
          image: sameer014/skmirza-wanderlust-frontend:1.0.0
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: skmirza-frontend-service
  namespace: wanderlust
spec:
  type: NodePort
  selector:
    app: skmizra-frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 31000
