apiVersion: apps/v1
kind: Deployment
metadata:
  name: skmirza-mongo-deploy
  namespace: wanderlust
  labels:
    app: skmirza-mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skmirza-mongo
  template:
    metadata:
      name: skmirza-mongo
      labels:
        app: skmirza-mongo
    spec:
      containers:
        - name: skmirza-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: skmirza-mongo-service
  namespace: wanderlust
spec:
  selector:
    app: skmirza-mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
