apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skmirza-mongo-pvc
  namespace: wanderlust
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
