apiVersion: apps/v1
kind: Deployment
metadata:
  name: skmirza-redis-deploy
  namespace: wanderlust
  labels:
    app: skmirza-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skmirza-redis
  template:
    metadata:
      name: skmirza-redis
      labels:
        app: skmirza-redis
    spec:
      containers:
        - name: skmirza-redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: mongo-storage
              mountPath: /var/lib/redis/dump.rdb
      volumes:
        - name: skmirza-mongo-storage
          persistentVolumeClaim:
            claimName: skmirza-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: skmirza-redis-service
  namespace: wanderlust
spec:
  selector:
    app: skmirza-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
